---

- name: Remove yum-cron to avoid yum automatic updates
  yum:
    name: yum-cron
    state: absent


- name: Remove PackageKit* yum packages
  yum:
    name:
      - PackageKit.i686
      - PackageKit.x86_64
      - PackageKit-device-rebind.x86_64
      - PackageKit-glib.x86_64
      - PackageKit-gtk-module.x86_64
      - PackageKit-yum.x86_64
      - PackageKit-yum-plugin.x86_64
      - PackageKit-backend-devel.i686
      - PackageKit-backend-devel.x86_64
      - PackageKit-browser-plugin.x86_64
      - PackageKit-command-not-found.x86_64
      - PackageKit-cron.x86_64
      - PackageKit-debug-install.x86_64
      - PackageKit-docs.noarch
      - PackageKit-glib.i686
      - PackageKit-glib.x86_64
      - PackageKit-glib-devel.i686
      - PackageKit-glib-devel.x86_64
      - PackageKit-gstreamer-plugin.x86_64
      - PackageKit-gtk-module.i686
      - PackageKit-gtk3-module.i686
      - PackageKit-gtk3-module.x86_64
      - PackageKit-qt.i686
      - PackageKit-qt.x86_64
      - PackageKit-qt-devel.i686
      - PackageKit-qt-devel.x86_64
      - PackageKit-Qt.x86_64
      - PackageKit-Qt-devel.x86_64
    state: absent


- name: Install epel-release yum package
  yum:
    name: epel-release
    state: present


- name: Install common required yum packages
  yum:
    name:
      - openssl
      - procmail
      - vim-enhanced
      - subversion
      - unzip
      - openssl
      - screen
      - xterm
      - ksh
      - wget
      - perl
      - net-snmp
      - rsync
      - telnet
      - iperf
      - vnstat
      - tree
    state: present
